import Link from "next/link";
import { Footer, PublicHeader } from "@/components/PublicChrome";
import { SupportChat } from "@/components/SupportChat";

export default function Home() {
  return <><PublicHeader /><main>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Field work, in rhythm</span><h1>Run the day.<br />Keep every promise.</h1><p>RelayOps is a local portfolio demo where service teams can inspect tenant-scoped operations and clearly labeled prewritten support states.</p><div className="hero-actions"><Link className="btn btn-primary" href="/demo">Explore the demo <span aria-hidden="true">→</span></Link><Link className="btn btn-secondary" href="/help">Browse the help centre</Link></div><div className="trust-row"><span>No card required</span><span>Local demo data</span><span>Built for small teams</span></div></div><div className="product-card" aria-label="RelayOps dashboard preview"><div className="product-bar"><b>Today at Northstar</b><span className="demo-pill">Simulated workspace</span></div><div className="mini-app"><div className="mini-top"><div><small className="muted">Synthetic seeded workspace</small><h3 style={{ margin: "3px 0" }}>Good morning, Maya</h3></div><span className="tenant-logo">NH</span></div><div className="mini-metrics"><div className="mini-metric"><small>Open jobs</small><b>2</b></div><div className="mini-metric"><small>Customers</small><b>2</b></div><div className="mini-metric"><small>Team seats</small><b>3</b></div></div><div className="mini-list"><div className="mini-row"><span>Lakeview Bakery</span><b style={{ color: "var(--teal)" }}>In progress</b></div><div className="mini-row"><span>Juniper Dental</span><b>Scheduled</b></div><div className="mini-row"><span>Support tickets</span><b>2 records</b></div></div></div></div></div></section>
    <section className="section" id="features"><div className="container"><div className="section-heading center"><span className="eyebrow">A clearer working day</span><h2>Everything the crew needs. Nothing in the way.</h2><p>From the first call to the final follow-up, RelayOps keeps context close and next steps obvious.</p></div><div className="feature-grid"><article className="feature-card"><div className="icon-box">⌁</div><h3>Dispatch without the scramble</h3><p>See today’s work, assignment status, and customer details in one responsive schedule.</p></article><article className="feature-card"><div className="icon-box">◎</div><h3>Give the team context</h3><p>Keep roles, job history, and clear handoffs connected to the workspace where they belong.</p></article><article className="feature-card"><div className="icon-box">✦</div><h3>Support with visible sources</h3><p>Preview an assistant experience that separates documentation citations from tenant account evidence.</p></article></div></div></section>
    <section className="section section-soft"><div className="container split"><div className="support-demo"><div className="support-demo-head"><span className="logo-mark" /><div><b>Relay support</b><div className="small muted"><span className="status-dot" style={{ display: "inline-block", marginRight: 5 }} />Simulated experience</div></div></div><div className="chat-body"><div className="bubble user">How do I invite another technician?</div><div className="bubble assistant">Open <b>Team</b>, choose <b>Invite member</b>, and select a role. Pending invitations use a seat.<div className="citation">↗ Invite your team and manage seats</div></div></div><div className="source-preview"><b>Exact source preview</b><p className="muted" style={{ margin: "6px 0 0" }}>“Each active member and pending invitation uses one seat…”</p></div></div><div><span className="eyebrow">Answers you can inspect</span><h2>Helpful, with the evidence left on.</h2><p className="muted" style={{ lineHeight: 1.7 }}>The support experience is designed to cite public guidance, label synthetic account facts, refuse cross-workspace requests, and make human handoff explicit.</p><div className="simulated-label" style={{ marginTop: 20 }}>Portfolio note: support interactions are deterministic local fixtures. No model, retrieval pipeline, live citation, account tool, or ticket-creation service is running.</div><Link className="btn btn-secondary" href="/dashboard/support">Explore every support state</Link></div></div></section>
    <section className="section" id="pricing"><div className="container"><div className="section-heading"><span className="eyebrow">Simple fictional pricing</span><h2>Room to grow, without guesswork.</h2><p>Pricing is illustrative only. This portfolio demo never collects payment details.</p></div><div className="pricing-grid"><article className="price-card"><h3>Starter</h3><p className="muted">For a small crew building a consistent day.</p><div className="price">$69 <span>/ month</span></div><ul className="check-list"><li>4 team seats</li><li>Scheduling and customers</li><li>Public help centre</li></ul><Link href="/demo" className="btn btn-secondary">View Starter demo</Link></article><article className="price-card featured"><span className="pill tag">Most popular</span><h3>Growth</h3><p className="muted">For teams coordinating more people and work.</p><div className="price">$129 <span>/ month</span></div><ul className="check-list"><li>8 team seats</li><li>Team and performance views</li><li>Account-aware support preview</li></ul><Link href="/demo" className="btn btn-primary">View Growth demo</Link></article><article className="price-card"><h3>Scale</h3><p className="muted">For established multi-crew operators.</p><div className="price">$229 <span>/ month</span></div><ul className="check-list"><li>20 team seats</li><li>Advanced permissions</li><li>Priority handoff</li></ul><Link href="/demo" className="btn btn-secondary">Explore the product</Link></article></div></div></section>
    <section className="section"><div className="container trust-panel"><div><span className="eyebrow" style={{ color: "#8ed8c2" }}>Trust by design</span><h2>Clear boundaries are part of the experience.</h2><p>This UI demonstrates how tenant identity, evidence labels, cautious refusals, and simulation notices can stay visible instead of being buried.</p></div><div className="trust-items"><div className="trust-item"><h3>Workspace identity</h3><span>The selected fictional tenant stays visible throughout the dashboard.</span></div><div className="trust-item"><h3>Evidence labels</h3><span>Documentation and account facts use distinct visual treatments.</span></div><div className="trust-item"><h3>Safe refusal</h3><span>Cross-workspace requests receive a direct boundary reminder.</span></div><div className="trust-item"><h3>Honest demo scope</h3><span>No claims of production security, AI accuracy, or customer outcomes.</span></div></div></div></section>
  </main><Footer /><SupportChat /></>;
}
