"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import type { ChatScenario, Section, TenantId, TenantSummary, Workspace } from "@/lib/contracts";
import { relayOpsService } from "@/lib/service";
import { Brand } from "./PublicChrome";
import { SupportChat } from "./SupportChat";

const nav: { section: Section; label: string; icon: string }[] = [
  { section: "overview", label: "Overview", icon: "⌂" }, { section: "jobs", label: "Jobs", icon: "▣" }, { section: "team", label: "Team", icon: "♙" }, { section: "customers", label: "Customers", icon: "♧" }, { section: "subscription", label: "Subscription", icon: "◫" }, { section: "support", label: "Support tickets", icon: "◌" }, { section: "knowledge", label: "Knowledge", icon: "◇" },
];
export function DashboardShell() {
  const pathname = usePathname(); const section = (pathname.split("/").pop() || "overview") as Section;
  const [tenants, setTenants] = useState<TenantSummary[]>([]); const [tenantId, setTenantId] = useState<TenantId | null>(null); const [data, setData] = useState<Workspace | null>(null); const [menu, setMenu] = useState(false); const [switcher, setSwitcher] = useState(false);
  useEffect(() => { void relayOpsService.listTenants().then((items) => { setTenants(items); const saved = localStorage.getItem("relayops-demo-tenant"); const selected = items.find((item) => item.id === saved)?.id ?? items[0]?.id; setTenantId(selected ?? null); }); }, []);
  useEffect(() => { if (tenantId) { setData(null); localStorage.setItem("relayops-demo-tenant", tenantId); void relayOpsService.getWorkspace(tenantId).then(setData); } }, [tenantId]);
  if (!data) return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", background: "var(--paper)" }}><div style={{ textAlign: "center" }}><span className="logo-mark" style={{ margin: "auto" }} /><p className="muted">Loading local workspace…</p></div></main>;
  return <div className="dashboard"><div className={`mobile-overlay ${menu ? "open" : ""}`} onClick={() => setMenu(false)} /><aside className={`sidebar ${menu ? "open" : ""}`}><Brand inverse /><div style={{ position: "relative" }}><button className="workspace-switch" onClick={() => setSwitcher(!switcher)} aria-expanded={switcher}><span className="tenant-logo">{data.tenant.initials}</span><span><b>{data.tenant.name}</b><small>{data.tenant.plan} · Demo</small></span><span aria-hidden="true">⌄</span></button>{switcher && <div style={{ position: "absolute", background: "white", color: "var(--ink)", borderRadius: 10, padding: 7, zIndex: 2, width: "100%", top: 52, boxShadow: "var(--shadow)" }}>{tenants.map((tenant) => <button key={tenant.id} onClick={() => { setTenantId(tenant.id); setSwitcher(false); }} className="tenant-choice" style={{ margin: 0, border: 0, padding: 8 }}><span className="tenant-logo" style={{ width: 30, height: 30, fontSize: 11 }}>{tenant.initials}</span><span><b>{tenant.name}</b><small>{tenant.plan}</small></span></button>)}</div>}</div><nav className="dash-nav" aria-label="Dashboard navigation">{nav.map((item) => <Link key={item.section} href={`/dashboard/${item.section}`} className={section === item.section ? "active" : ""} onClick={() => setMenu(false)}><span className="nav-icon" aria-hidden="true">{item.icon}</span>{item.label}</Link>)}</nav><div className="sidebar-bottom"><div className="user-row"><span className="avatar">MS</span><span><b className="small">Demo operator</b><small>Workspace owner</small></span></div></div></aside><main className="dash-main"><header className="dash-top"><div style={{ display: "flex", alignItems: "center", gap: 10 }}><button className="mobile-menu" onClick={() => setMenu(true)} aria-label="Open navigation">☰</button><b>{nav.find((item) => item.section === section)?.label}</b></div><div className="dash-top-actions"><Link className="btn btn-secondary small" href="/help">Help centre</Link><span className="avatar" title="Demo operator">MS</span></div></header><div className="demo-banner"><b>SIMULATED WORKSPACE</b> · Data is local, synthetic, and resets with your browser.</div><div className="dash-content"><SectionView section={section} data={data} /></div></main></div>;
}
function Head({ title, description, action }: { title: string; description: string; action?: string }) { return <div className="page-head"><div><h1>{title}</h1><p>{description}</p></div>{action && <button className="btn btn-primary">{action}</button>}</div>; }
function Status({ value }: { value: string }) { return <span className={`status ${value}`}>{value}</span>; }
function SectionView({ section, data }: { section: Section; data: Workspace }) {
  if (section === "overview") return <><Head title={`Good morning, ${data.tenant.name.split(" ")[0]}`} description={`Here’s what’s moving at ${data.tenant.name} today.`} action="+ New job" /><div className="metric-grid">{data.metrics.map((m) => <div className="metric-card" key={m.label}><span className="metric-label">{m.label}</span><span className="metric-value">{m.value}</span><span className={`metric-note ${m.trend ?? ""}`}>{m.note}</span></div>)}</div><div className="dash-grid"><div className="panel"><div className="panel-head"><h2>Today’s schedule</h2><Link className="small" href="/dashboard/jobs" style={{ color: "var(--teal)", fontWeight: 700 }}>View all</Link></div><JobsTable data={data} compact /></div><div className="panel"><div className="panel-head"><h2>Live activity</h2></div><div className="activity">{data.activity.map((a) => <div className="activity-row" key={a.text}><i className="activity-dot" /><div>{a.text}<span>{a.time}</span></div></div>)}</div></div></div></>;
  if (section === "jobs") return <><Head title="Jobs" description={`${data.jobs.length} visible synthetic jobs for ${data.tenant.name}.`} action="+ New job" /><div className="panel"><div className="panel-head"><h2>Schedule</h2><button className="btn btn-secondary small">Filter · All</button></div><JobsTable data={data} /></div></>;
  if (section === "team") return <><Head title="Team" description="Manage roles, invitations, and seat visibility." action="Invite member" /><div className="settings-grid" style={{ marginBottom: 16 }}><div className="panel usage-box"><div className="usage-line"><b>Team seats</b><b>{data.subscription.seatsUsed} / {data.subscription.seatsTotal}</b></div><div className="progress"><span style={{ width: `${data.subscription.seatsUsed / data.subscription.seatsTotal * 100}%` }} /></div>{data.subscription.seatsUsed === data.subscription.seatsTotal && <div className="callout"><b>All included seats are in use.</b><br />Pending invitations count as seats. Revoke one or preview a plan change before inviting another member.</div>}</div><div className="panel usage-box"><b>Roles stay workspace-scoped</b><p className="muted small" style={{ lineHeight: 1.6, marginTop: 10 }}>This demo shows role labels only. It does not enforce authentication or permissions.</p></div></div><div className="panel table-wrap"><table className="data-table"><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{data.members.map((m) => <tr key={m.email}><td><strong>{m.name}</strong><small>{m.email}</small></td><td>{m.role}</td><td><Status value={m.status} /></td><td><button className="btn btn-quiet">•••</button></td></tr>)}</tbody></table></div></>;
  if (section === "customers") return <><Head title="Customers" description={`Synthetic customer records scoped to ${data.tenant.name}.`} action="+ Add customer" /><div className="panel table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Address</th><th>Last service</th><th>Jobs</th><th>Lifetime value</th></tr></thead><tbody>{data.customers.map((c) => <tr key={c.name}><td><strong>{c.name}</strong></td><td>{c.address}</td><td>{c.lastService}</td><td>{c.jobs}</td><td>{c.value}</td></tr>)}</tbody></table></div></>;
  if (section === "subscription") return <><Head title="Subscription" description="Illustrative plan and seat usage—no billing system is connected." /><div className="settings-grid"><div className="panel usage-box"><span className="pill">Current plan</span><h2 style={{ fontSize: "1.8rem", margin: "15px 0 5px" }}>{data.subscription.plan}</h2><p className="muted">{data.subscription.amount} · renews {data.subscription.renewal}</p><button className="btn btn-secondary">Preview plans</button></div><div className="panel usage-box"><div className="usage-line"><b>Included seats</b><b>{data.subscription.seatsUsed} of {data.subscription.seatsTotal}</b></div><div className="progress"><span style={{ width: `${data.subscription.seatsUsed / data.subscription.seatsTotal * 100}%` }} /></div><p className="muted small" style={{ lineHeight: 1.6, marginTop: 15 }}>Active members and pending invitations both use a seat.</p></div></div><div className="callout"><b>Billing is a visual demo.</b> Plan changes, invoices, charges, and payment methods are not implemented.</div></>;
  if (section === "support") return <SupportScreen data={data} />;
  return <KnowledgeScreen data={data} />;
}
function JobsTable({ data, compact = false }: { data: Workspace; compact?: boolean }) { const jobs = compact ? data.jobs.slice(0, 3) : data.jobs; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Job</th><th>Customer</th><th>Technician</th><th>Time</th><th>Status</th></tr></thead><tbody>{jobs.map((j) => <tr key={j.id}><td><strong>{j.id}</strong><small>{j.service}</small></td><td>{j.customer}</td><td>{j.assignee}</td><td>{j.time}</td><td><Status value={j.status} /></td></tr>)}</tbody></table></div>; }
function SupportScreen({ data }: { data: Workspace }) { const [scenario, setScenario] = useState<ChatScenario>("seats"); const options: { value: ChatScenario; label: string }[] = [{ value: "public", label: "Public question + citation" }, { value: "seats", label: "Docs + account seat limit" }, { value: "refusal", label: "Cross-tenant refusal" }, { value: "handoff", label: "Handoff confirmation" }, { value: "error", label: "Request error" }, { value: "quota", label: "Free quota reached" }, { value: "unavailable", label: "Account tools unavailable" }]; return <><Head title="Support experience" description={`Inspect deterministic UI states for ${data.tenant.name}. No AI or ticket backend is connected.`} /><div className="full-support"><aside className="panel scenario-panel"><h2>Simulation controls</h2><p className="muted small">Select a state to replay it.</p>{options.map((o) => <button className={scenario === o.value ? "active" : ""} onClick={() => setScenario(o.value)} key={o.value}>{o.label}</button>)}<div className="state-strip"><span className="state-chip">Closed/open</span><span className="state-chip">Loading</span><span className="state-chip">Success</span><span className="state-chip error">Error</span></div></aside><div className="panel support-console"><SupportChat embedded tenantId={data.tenant.id} forcedScenario={scenario} /></div></div><div className="panel table-wrap" style={{ marginTop: 16 }}><div className="panel-head"><h2>Recent support tickets</h2><span className="small muted">Synthetic records</span></div><table className="data-table"><thead><tr><th>Ticket</th><th>Subject</th><th>Requester</th><th>Status</th><th>Updated</th></tr></thead><tbody>{data.tickets.map((ticket) => <tr key={ticket.id}><td><strong>{ticket.id}</strong></td><td>{ticket.subject}</td><td>{ticket.requester}</td><td><Status value={ticket.status} /></td><td>{ticket.updated}</td></tr>)}</tbody></table></div></> }
function KnowledgeScreen({ data }: { data: Workspace }) { return <><Head title="Knowledge" description="Review public support content before it is published." action="+ New article" /><div className="knowledge-editor"><div><div className="panel table-wrap" style={{ marginBottom: 16 }}><table className="data-table"><thead><tr><th>Article</th><th>Category</th><th>Status</th><th>Views</th></tr></thead><tbody>{data.knowledge.map((k) => <tr key={k.title}><td><strong>{k.title}</strong><small>Updated {k.updated}</small></td><td>{k.category}</td><td><Status value={k.status} /></td><td>{k.views}</td></tr>)}</tbody></table></div><div className="panel editor"><span className="eyebrow">Draft editor</span><h2 style={{ fontSize: "1.3rem", margin: "8px 0 20px" }}>{data.knowledge.find((k) => k.status === "Draft")?.title}</h2><div className="field"><label htmlFor="article-title">Article title</label><input id="article-title" defaultValue={data.knowledge.find((k) => k.status === "Draft")?.title} /></div><div className="field"><label htmlFor="article-body">Content</label><textarea id="article-body" defaultValue={"Help customers prepare before seasonal service.\n\nAdd verified steps here, then review audience and sources before publishing."} /></div><button className="btn btn-primary">Save local draft</button></div></div><aside className="panel usage-box"><h3>Publishing checklist</h3><ul className="check-list small"><li>Title is specific</li><li>Steps are verified</li><li>Audience is correct</li><li>Links are current</li></ul><div className="simulated-label"><b>Not persisted.</b> Edits reset on refresh and are never published.</div></aside></div></> }
