"use client";
import React, { useEffect, useState } from 'react';
import type { KnowledgeRun, KnowledgeSearchHit, KnowledgeSnapshot, RagClient } from '@/lib/rag-contracts';
import { relayOpsService } from '@/lib/service';

export function KnowledgeConsole({ client = relayOpsService.support }: { client?: RagClient }) {
  const [snapshot, setSnapshot] = useState<KnowledgeSnapshot | null>(null); const [selected, setSelected] = useState<string | null>(null); const [query, setQuery] = useState(''); const [hits, setHits] = useState<KnowledgeSearchHit[]>([]);
  const [loading, setLoading] = useState(true); const [searching, setSearching] = useState(false); const [reindexing, setReindexing] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [failure, setFailure] = useState<string | null>(null);
  useEffect(() => { void load(); }, []);
  async function load() { setLoading(true); setFailure(null); try { setSnapshot(await client.getKnowledge()); } catch (cause) { setFailure(cause instanceof Error ? cause.message : 'Knowledge could not be loaded.'); } finally { setLoading(false); } }
  async function search(event: React.FormEvent) { event.preventDefault(); if (!query.trim()) { setHits([]); return; } setSearching(true); setFailure(null); try { setHits(await client.searchKnowledge(query)); } catch (cause) { setFailure(cause instanceof Error ? cause.message : 'Evidence search failed.'); } finally { setSearching(false); } }
  async function reindex(logicalId?: string) { setReindexing(logicalId ?? 'all'); setMessage(null); setFailure(null); try { const result = await client.reindexKnowledge(logicalId); setMessage(result.results.every((item) => item.status !== 'failed') ? 'Committed manifest reindex completed. Previous active versions were retained where work was skipped.' : 'One or more committed manifest sources failed; previous active versions were retained.'); await load(); } catch (cause) { setFailure(cause instanceof Error ? cause.message : 'Reindex failed without changing an active version.'); } finally { setReindexing(null); } }
  if (loading) return <div className="panel knowledge-loading" role="status">Loading live local Knowledge state…</div>;
  if (!snapshot) return <div className="error-panel" role="alert">{failure ?? 'Knowledge could not be loaded.'} <button className="btn btn-secondary" onClick={() => void load()}>Retry</button></div>;
  const active = snapshot.sources.filter((source) => source.status === 'active');
  return <div className="knowledge-console">
    <div className="simulated-label"><b>Owner-only local observability.</b> Sources are the committed public manifest. This console accepts only its allowlisted logical IDs, never a path, URL, corpus body, tenant, or model setting.</div>
    {message && <div className="inline-success" role="status">{message}</div>}{failure && <div className="inline-error" role="alert">{failure}</div>}
    <div className="knowledge-summary-grid"><div className="metric-card"><span className="metric-label">Active sources</span><span className="metric-value">{active.length}</span><span className="metric-note">Only active versions can be cited</span></div><div className="metric-card"><span className="metric-label">Latest run</span><span className="metric-value">{snapshot.runs[0]?.stage ?? '—'}</span><span className="metric-note">Failure preserves prior active evidence</span></div><div className="metric-card"><span className="metric-label">MiniLM cache</span><span className="metric-value">{snapshot.model.status}</span><span className="metric-note">{snapshot.model.cache} · local only</span></div></div>
    <div className="knowledge-grid"><section className="panel"><div className="panel-head"><div><h2>Sources and active versions</h2><span className="small muted">Public evidence namespace only</span></div><div><button className="btn btn-secondary small" onClick={() => void reindex()} disabled={Boolean(reindexing)}>{reindexing === 'all' ? 'Reindexing…' : 'Reindex manifest'}</button> <button className="btn btn-secondary small" onClick={() => void load()}>Refresh</button></div></div><div className="source-list">{snapshot.sources.map((source) => <article className={`source-row ${selected === source.logicalId ? 'selected' : ''}`} key={source.logicalId}><button onClick={() => setSelected(selected === source.logicalId ? null : source.logicalId)} aria-expanded={selected === source.logicalId}><span><b>{source.title}</b><small>{source.logicalId} · {source.status} · {source.chunkCount} active chunks</small></span><span aria-hidden="true">{selected === source.logicalId ? '⌃' : '⌄'}</span></button>{selected === source.logicalId && <div className="source-detail"><dl><div><dt>Type</dt><dd>{source.sourceType}</dd></div><div><dt>Active version</dt><dd>{source.activeVersion ?? 'None'}</dd></div><div><dt>Updated</dt><dd>{new Date(source.updatedAt).toLocaleDateString()}</dd></div></dl><button className="btn btn-secondary small" onClick={() => void reindex(source.logicalId)} disabled={Boolean(reindexing)}>{reindexing === source.logicalId ? 'Reindexing…' : 'Reindex committed source'}</button></div>}</article>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Ingestion runs</h2><span className="small muted">Sanitized lifecycle and failure visibility</span></div></div><div className="run-list">{snapshot.runs.map((run) => <RunRow run={run} key={run.id} />)}</div></section></div>
    <section className="panel model-panel"><div><span className="eyebrow">Model and cache status</span><h2>{snapshot.model.name}</h2><p className="muted">{snapshot.model.note}</p></div><div className="model-status"><span className={`status ${snapshot.model.status}`}>{snapshot.model.status}</span><span className="small">Cache: {snapshot.model.cache}</span></div></section>
    <section className="panel inspector"><div className="panel-head"><div><h2>Chunk and evidence inspector</h2><span className="small muted">Searches active committed public evidence only</span></div></div><form className="inspector-form" onSubmit={search}><label className="sr-only" htmlFor="knowledge-search">Search evidence chunks</label><input id="knowledge-search" value={query} onChange={(event) => setQuery(event.target.value)} maxLength={500} placeholder="Search active chunks, headings, or source text…" /><button className="btn btn-primary" disabled={searching}>{searching ? 'Searching…' : 'Search'}</button></form>{query && !searching && <div className="search-results" aria-live="polite">{hits.length ? hits.map((hit) => <article className="evidence citation-card" key={hit.citation.evidenceId}><span className="evidence-type">Active evidence · score {hit.score.toFixed(2)}</span><b>{hit.citation.sourceTitle}{hit.citation.heading ? ` · ${hit.citation.heading}` : ''}</b><p>{hit.citation.excerpt}</p><small>{hit.citation.page ? `Page ${hit.citation.page}` : 'No page supplied'}{hit.citation.anchor ? ` · #${hit.citation.anchor}` : ''}</small></article>) : <div className="empty-state">No active public evidence matched this query.</div>}</div>}</section>
  </div>;
}
function RunRow({ run }: { run: KnowledgeRun }) { return <article className="run-row"><div><b>{run.sourceLogicalId}</b><small>{new Date(run.startedAt).toLocaleString()} · {run.id}</small></div><span className={`status ${run.status}`}>{run.status} · {run.stage}</span>{run.error && <p role="alert">Failure: {run.error}</p>}</article>; }
